name: medication_remainder
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  antdesign_icons: ^0.0.3
  cupertino_icons: ^1.0.2
  date_picker_timeline: ^1.2.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^12.0.4
  flutter_native_timezone: ^2.0.0
  flutter_phone_direct_caller: ^2.1.1
  flutter_staggered_animations: ^1.1.1
  google_maps_flutter_web: ^0.3.0+3
  dio: ^4.0.0
  connectivity_plus: ^1.0.7
  location: ^4.3.0
  permission_handler: ^8.1.4+2
  flutter_svg: ^0.22.0
  fluster: ^1.2.0
  cached_network_image: ^3.1.0
  flutter_rating_bar: ^4.0.0
  fluttertoast: ^8.0.8
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.0.6
  http: ^0.13.5
  intl: ^0.17.0
  lottie: ^2.0.0
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  sqflite: ^2.2.2
  twilio_flutter: ^0.0.9
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/auth/
    - assets/style/
    - assets/marker/
    - assets/placeholder/

  fonts:
    - family: Mulish
      fonts:
        - asset: fonts/Mulish-Light.ttf
        - asset: fonts/Mulish-SemiBold.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
